name: "Pull Request Labeler"
on:
    - pull_request_target

jobs:
    triage:
        permissions:
            contents: read
            pull-requests: write
        runs-on: ebpf-linux
        steps:
            - uses: actions/labeler@v4
              with:
                  repo-token: "${{ secrets.GITHUB_TOKEN }}"
